<!DOCTYPE html><html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>404 - Page Not Found</title>
    <link rel="shortcut icon" href="<?=base_url()?>favicon.ico">
    <link rel="stylesheet" type="text/css" href="<?=base_url()?>contents/css/error.css"/>
    <script type="text/javascript" src="<?=base_url()?>contents/js/jquery.js"></script>
    <script type="text/javascript">$(function(){/* 4 */ $(this).delay(1500).queue(function(){$( ".one" ).addClass("selected");$(this).dequeue();})/* 0 */ .delay(500).queue(function(){$( ".two" ).addClass("selected");$(this).dequeue();})/* 4 */ .delay(500).queue(function(){$( ".three" ).addClass("selected");$(this).dequeue();})/* P */ .delay(500).queue(function(){$( ".four" ).addClass("selected");$(this).dequeue();})/* A */ .delay(500).queue(function(){$( ".five" ).addClass("selected");$(this).dequeue();})/* G */ .delay(500).queue(function(){$( ".six" ).addClass("selected");$(this).dequeue();})/* E */ .delay(500).queue(function(){$( ".seven" ).addClass("selected");$(this).dequeue();})/* N */ .delay(500).queue(function(){$( ".eight" ).addClass("selected");$(this).dequeue();})/* O */ .delay(500).queue(function(){$( ".nine" ).addClass("selected");$(this).dequeue();})/* T */ .delay(500).queue(function(){$( ".ten" ).addClass("selected");$(this).dequeue();})/* F */ .delay(500).queue(function(){$( ".eleven" ).addClass("selected");$(this).dequeue();})/* O */ .delay(500).queue(function(){$( ".twelve" ).addClass("selected");$(this).dequeue();})/* U */ .delay(500).queue(function(){$( ".thirteen" ).addClass("selected");$(this).dequeue();})/* N */ .delay(500).queue(function(){$( ".fourteen" ).addClass("selected");$(this).dequeue();})/* D */ .delay(500).queue(function(){$( ".fifteen" ).addClass("selected");$(this).dequeue();});});</script>

    <script type="text/javascript">$(function(){var liWidth=$("li").css("width");$("li").css("height",liWidth);$("li").css("lineHeight",liWidth);var totalHeight=$("#wordsearch").css("width");$("#wordsearch").css("height",totalHeight);});causeRepaintsOn=$("h1, h2, h3, p");$(window).resize(function(){causeRepaintsOn.css("z-index", 1);});$(window).on('resize', function(){var liWidth=$(".one").css("width");$("li").css("height",liWidth);$("li").css("lineHeight",liWidth);var totalHeight=$("#wordsearch").css("width");$("#wordsearch").css("height",totalHeight);});</script>

</head>
<body>
    <noscript><div id="noscript-warning">This site works best with Javascript enabled, as you can plainly see.</div></noscript><div id="wrap"><div id="wordsearch"><ul><li>e</li><li>t</li><li>a</li><li>d</li><li>z</li><li>r</li><li>x</li><li>i</li><li>m</li><li>h</li><li>y</li><li>r</li><li>z</li><li>k</li><li>m</li><li>u</li><li>x</li><li>a</li><li>m</li><li>b</li><li class="one">4</li><li class="two">0</li><li class="three">4</li><li>p</li><li>n</li><li>i</li><li>t</li><li>i</li><li>n</li><li>v</li><li>o</li><li>a</li><li>i</li><li>s</li><li class="four">p</li><li class="five">a</li><li class="six">g</li><li class="seven">e</li><li>o</li><li>l</li><li>l</li><li>e</li><li class="eight">n</li><li class="nine">o</li><li class="ten">t</li><li>p</li><li>k</li><li>d</li><li>q</li><li>e</li><li>q</li><li>c</li><li>f</li><li>b</li><li>j</li><li>k</li><li>e</li><li>r</li><li class="eleven">f</li><li class="twelve">o</li><li class="thirteen">u</li><li class="fourteen">n</li><li class="fifteen">d</li><li>m</li></ul></div><div id="main-content"><h1>Oops! <br>We couldn't find what you were looking for.</h1><p>It's looking like you may have taken a wrong turn.<br>Don't worry... it happens to the best of us.<br>Check the URL or here's a little map that might help you get back on track :</p>
    <div id="navigation">
        <a class="navigation" href="<?=base_url()?>">Home</a>
        <a class="navigation" href="<?=base_url()?>about_us">About Us</a>
        <a class="navigation" href="<?=base_url()?>status">Status</a>
        </div></div></div></body>
</html>